### ISSUE TITLE
Ne s'affiche pas

### ISSUE THREAD

**Issue by cesagonchu** [alain01/cockpit-by-monxoops#4]
J'ai envoyé le dossier cockpit-by-monxoops vers /modules/system/themes/
J'ai mis à jour le module système
Le thème admin n'apparait pas dans le menu déroulant Control Panel GUI.

___
Ma config :

PHP 7.4.9
MYSQL 5.7.33-0ubuntu0.16.04.1
XOOPS 2.5.11-Beta2 (d'aujourd'hui)
cockpit-by-monxoops d'aujourd'hui

**Comment by alain01** [comment]
Bonsoir,
pour l'instant, il faut remplacer le module system entier
c'est à dire prendre le paquet téléchargé et "écraser" le module system.
C'est bien sur une version en début de dev, pas aboutie, une piste vers quoi tendre.

**Comment by cesagonchu** [comment]
Ah ok du coup je testerai plus tard car je ne souhaite pas modifier mon Xoops de test :)

**Comment by alain01** [comment]
Tu peux le renommer ;-) system.ref

**Comment by cesagonchu** [comment]
Oui pas con :p

**Comment by alain01** [comment]
Attention, Il faudra choisir un thème admin d'origine avant de  remettre le module system original
